<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-J20IS8F" failures="1" tests="3" name="Test2" time="18.091" errors="0" timestamp="2024-08-08T12:54:28 IST">
  <testcase classname="coverFoxTest.CoverFoxTC2" name="validateMobileNoErrorMsgColor" time="0.058"/>
  <testcase classname="coverFoxTest.CoverFoxTC2" name="validateMobileNumberErrorMessage" time="0.05"/>
  <testcase classname="coverFoxTest.CoverFoxTC2" name="validatePinCodeErrorMessage" time="0.001">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at coverFoxTest.CoverFoxTC2.validatePinCodeErrorMessage(CoverFoxTC2.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- validatePinCodeErrorMessage -->
</testsuite> <!-- Test2 -->
